# -*- coding: utf-8 -*-
"""Visualization with matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMFAbSkdVYUTu3qCIIhJSLX2107U8_rj

pl.plot() creates a line plot.

pl.title(), pl.xlabel(), and pl.ylabel() add titles and labels to your plot.

pl.show() displays the plot.

**Basic Plotting with Matplotlib**
"""

import matplotlib.pyplot as pl

# Sample data
x = [1, 20, 30, 40, 50]
y = [2, 3, 5, 7, 11]

# Creating a basic line plot
pl.plot(x, y)
pl.title('Basic Line Plot')
pl.xlabel('X-axis Label')
pl.ylabel('Y-axis Label')
pl.show()

"""**Customizing Plots in Matplotlib**

Changing Line Styles and Colors
"""

pl.plot(x, y, color='red', linestyle='--', marker='o')
pl.title('Customized Line Plot')
pl.xlabel('X-axis Label')
pl.ylabel('Y-axis Label')
pl.show()

"""**Plotting Different Types of Charts in Matplotlib**

Bar Charts
"""

categories = ['A', 'B', 'C', 'D']
values = [5, 7, 3, 8]

pl.bar(categories, values, color='blue')
pl.title('Bar Chart Example')
pl.xlabel('Categories')
pl.ylabel('Values')
pl.show()

"""Histograms"""

import numpy as np

data = np.random.randn(1000)

pl.hist(data, bins=30, color='purple', edgecolor='black')
pl.title('Histogram Example')
pl.xlabel('Data Bins')
pl.ylabel('Frequency')
pl.show()

"""**Creating Plots with Seaborn**

Scatter Plots
"""

import seaborn as sn
import matplotlib.pyplot as pl

# Load the built-in dataset
tips = sn.load_dataset('tips')

# Creating a scatter plot
sn.scatterplot(x='total_bill', y='tip', data=tips, hue='sex')
pl.title('Scatter Plot of Tips vs. Total Bill')
pl.xlabel('Total Bill ($)')
pl.ylabel('Tip ($)')
pl.show()

"""Box Plots"""

sn.boxplot(x='day', y='total_bill', data=tips, palette='Set2')
pl.title('Box Plot Example')
pl.xlabel('Day')
pl.ylabel('Total Bill')
pl.show()